language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
env:
  - DJANGO_SECRET_KEY="deadcafebabe" DJANGO_DS_API_KEY="deadcafebabe"
script:
  - python manage.py test
  - flake8
after_success:
  - coveralls
