# Generated by Django 2.2 on 2020-05-22 17:12

from django.db import migrations, models


def set_default_booker(apps, schema_editor):
    Booking = apps.get_model('website', 'Booking')
    for booking in Booking.objects.all().iterator():
        if booking.user.first_name and booking.user.last_name:
            booking.booker = f'{booking.user.first_name} {booking.user.last_name}'
        elif booking.user.first_name:
            booking.booker = f'{booking.user.first_name}'
        else:
            booking.booker = booking.user
        booking.save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sort_images_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booker',
            field=models.CharField(null=True, max_length=100, verbose_name='Booker'),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_booker),
        migrations.AlterField(
            model_name='booking',
            name='booker',
            field=models.CharField(max_length=100, verbose_name='Booker'),
        ),
    ]
