# Generated by Django 3.1.6 on 2021-04-25 12:04

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_booking_booker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('content', markdownx.models.MarkdownxField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Tips for Trips',
                'verbose_name_plural': 'Tips for Trips',
            },
        ),
    ]
