name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install apt dependencies
        run: sudo apt update && sudo apt install -y gettext

      - name: Install pip dependencies
        run: pip install -r requirements.txt

      - name: Compile messages
        run: python manage.py compilemessages

      - name: Run tests
        run: coverage run --omit=*/tests/* manage.py test

      - name: Run flake8
        run: flake8

      - name: Coveralls
        run: coveralls --service=github
